services:
  postgres:
    image: postgres:17.5-alpine
    container_name: my-app-pg-db
    ports:
      - "3402:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  py-api:
    build:
      context: ./my-app-py-api
      dockerfile: Dockerfile.dev
    container_name: my-app-py-api
    ports:
      - "3401:3401"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - postgres
    volumes:
      - ./my-app-py-api:/my-app/py-api

  flyway:
    build:
      context: ./my-app-db-migrations
      dockerfile: Dockerfile
    container_name: my-app-db-migrations
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - postgres

volumes:
  postgres_data: